PROG ?= mongoose-rest-test
SSL = ?

ifeq "$(SSL)" "MBEDTLS"
CFLAGS += -DMG_ENABLE_MBEDTLS=1 -lmbedtls -lmbedcrypto -lmbedx509
endif

ifeq "$(SSL)" "OPENSSL"
CFLAGS += -DMG_ENABLE_OPENSSL=1 -lssl -lcrypto
endif

EXTRA_CFLAGS += -std=gnu99

all: $(PROG)

$(PROG): main.c
	$(CC) ./mg/mongoose.c -I./mg/ -W -Wall $(CFLAGS) $(EXTRA_CFLAGS) -o $(PROG) main.c

clean:
	rm -rf $(PROG) *.o *.dSYM *.gcov *.gcno *.gcda *.obj *.exe *.ilk *.pdb
